# Don't use something like ubuntu: latest
# We'll use an older Ubuntu version to help demo listing images later
FROM ubuntu:20.04

# There's more than one way to specify a command in Docker. This is the simplest way and,
## all things being equal, the preferred
# Note that this is JSON
CMD ["echo", "Hello World"]
